---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-micro.fullname" . }}
  labels:
    {{- include "k8s-micro.labels" . | nindent 4 }}
data:
  serviceconfig.yaml: |
    {{- include "k8s-micro.config" . | nindent 4 }}
  logback.xml: |
    {{- include "k8s-micro.logback" . | nindent 4 }}
