apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-micro.fullname" . }}
  labels:
    {{- include "k8s-micro.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http-web
      protocol: TCP
      name: http-web
    - name: http-envoy-prom
      port: 15020
      protocol: TCP
      targetPort: 15020
  selector:
    {{- include "k8s-micro.selectorLabels" . | nindent 4 }}
